#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OrarendAndroidApp.Resource", IsApplication=true)]

namespace OrarendAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cell_shape_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cell_shape_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cell_shape_selected_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cell_shape_selected_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_add_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_add_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_autorenew_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_autorenew_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_create_black_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_create_white_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_settings_black_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_settings_white_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int ScrollView01 = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int ScrollView02 = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int container = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int csoportokEditText = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int deleteButton = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int helyTV = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int horizontalView = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int kezdvegTV = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int kivoraTV = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int kovoraTV = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int menu_add = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int menu_edit = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int menu_fullrefresh = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int menu_preferences = 2131165208;
			
			// aapt resource value: 0x7f070015
			public const int menu_refresh = 2131165205;
			
			// aapt resource value: 0x7f070001
			public const int névEditText = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int osztalylistaTV = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int osztálySpinner = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int progressBar1 = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int saveButton = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int scrollLinearLayout = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int tableLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int textView3 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView4 = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int simple_list_item_1 = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main_menu_light = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ora_menu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
