#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OrarendAndroidApp.Resource", IsApplication=true)]

namespace OrarendAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cell_shape_added_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cell_shape_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cell_shape_removed_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cell_shape_selected_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_add_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_autorenew_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_create_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_settings_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int ScrollView01 = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int ScrollView02 = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int actionMenuView1 = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int container = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int csoportokEditText = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int deleteButton = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int helyTV = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int horizontalView = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int kezdvegTV = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int kivoraTV = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int kovoraTV = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int menu_add = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int menu_edit = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int menu_fullrefresh = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int menu_preferences = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int menu_refresh = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int névEditText = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int osztalylistaTV = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int osztálySpinner = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int progressBar1 = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int saveButton = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int scrollLinearLayout = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int spinner = 2131099670;
			
			// aapt resource value: 0x7f06000f
			public const int tableLayout1 = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView3 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textView4 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int simple_list_item_1 = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int main_menu_light = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
